project:
  type: default
  output-dir: docs
  render:
    - reports/qmd_example.qmd

format:
  html:
    toc: true
    toc-depth: 2
    number-sections: true
  pdf:
    toc: true
    toc-depth: 2
    number-sections: true